namespace Tiger;

public enum TfxRenderStage
{
    GenerateGbuffer = 0,
    RoadDecals = 1,
    Decals = 2,
    InvestmentDecals = 3,
    ShadowGenerate = 4,
    LightingApply = 5,
    LightProbeApply = 6,
    DecalsAdditive = 7,
    Transparents = 8,
    Distortion = 9,
    LightShaftOcclusion = 10,
    SkinPrepass = 11,
    LensFlares = 12,
    DepthPrepass = 13,
    WaterReflection = 14,
    PostprocessTransparentStencil = 15,
    Impulse = 16,
    Reticle = 17,
    WaterRipples = 18,
    MaskSunLight = 19,
    Volumetrics = 20,
    Cubemaps = 21,
    PostprocessScreen = 22,
    WorldForces = 23,
    ComputeSkinning = 24,
}

public enum TfxFeatureRenderer
{
    StaticObjects = 0,
    DynamicObjects = 1,
    ExampleEntity = 2,
    SkinnedObject = 3,
    Gear = 4,
    RigidObject = 5,
    Cloth = 6,
    ChunkedInstanceObjects = 7,
    SoftDeformable = 8,
    TerrainPatch = 9,
    SpeedtreeTrees = 10,
    EditorTerrainTile = 11,
    EditorMesh = 12,
    BatchedEditorMesh = 13,
    EditorDecal = 14,
    Particles = 15,
    ChunkedLights = 16,
    DeferredLights = 17,
    SkyTransparent = 18,
    Widget = 19,
    Decals = 20,
    DynamicDecals = 21,
    RoadDecals = 22,
    Water = 23,
    LensFlares = 24,
    Volumetrics = 25,
    Cubemaps = 26,
}

public enum TfxScope
{
    FRAME,
    VIEW,
    RIGID_MODEL,
    EDITOR_MESH,
    EDITOR_TERRAIN,
    CUI_VIEW,
    CUI_OBJECT,
    SKINNING,
    SPEEDTREE,
    CHUNK_MODEL,
    DECAL,
    INSTANCES,
    SPEEDTREE_LOD_DRAWCALL_DATA,
    TRANSPARENT,
    TRANSPARENT_ADVANCED,
    SDSM_BIAS_AND_SCALE_TEXTURES,
    TERRAIN,
    POSTPROCESS,
    CUI_BITMAP,
    CUI_STANDARD,
    UI_FONT,
    CUI_HUD,
    PARTICLE_TRANSFORMS,
    PARTICLE_LOCATION_METADATA,
    CUBEMAP_VOLUME,
    GEAR_PLATED_TEXTURES,
    GEAR_DYE_0,
    GEAR_DYE_1,
    GEAR_DYE_2,
    GEAR_DYE_DECAL,
    GENERIC_ARRAY,
    GEAR_DYE_SKIN,
    GEAR_DYE_LIPS,
    GEAR_DYE_HAIR,
    GEAR_DYE_FACIAL_LAYER_0_MASK,
    GEAR_DYE_FACIAL_LAYER_0_MATERIAL,
    GEAR_DYE_FACIAL_LAYER_1_MASK,
    GEAR_DYE_FACIAL_LAYER_1_MATERIAL,
    PLAYER_CENTERED_CASCADED_GRID,
    GEAR_DYE_012,
    COLOR_GRADING_UBERSHADER,
    CUI_DRAWING
}
